# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_topic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_topic',
            field=models.IntegerField(default=1),
        ),
    ]
