# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_topic_is_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='reply_count',
            field=models.IntegerField(default=1),
        ),
    ]
