# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_answer_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question_id',
        ),
    ]
