# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('is_work', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('homework_id', models.IntegerField(default=None)),
            ],
        ),
    ]
