# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_auto_20160520_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submit',
            old_name='content',
            new_name='up',
        ),
    ]
