# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20160520_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='up',
        ),
        migrations.AddField(
            model_name='submit',
            name='path',
            field=models.FileField(default=None, upload_to='./static/files'),
        ),
    ]
