# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_auto_20160520_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
