# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_submit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='is_work',
            field=models.IntegerField(default=2),
        ),
    ]
